Adding plans directly to the scheduler
material-motion/material-motion-runtime-android pull request #36
Opened 2016-10-14 20:34 UTC by seanoshea

This is a WIP.

2016-10-15 16:47 UTC, appsforartists commented on library/src/main/java/com/google/android/material/motion/runtime/Scheduler.java
> +   * @deprecated  Post version 1.0, plans should be added directly to the Scheduler instead of using Transactions. </br>
"Post version 1.0" feels unnecessary.

"Transactions are deprecated.  Commit plans directly with scheduler.addPlan(plan, target)"

2016-10-15 16:51 UTC, appsforartists commented
@pingpongboss watches this repo, so he should see your PRs without `@`ing the core team in every one.  You can always post a link to the PR in `discord/#android` too if you wanna draw attention to it.

I don't speak Java, so I typically refrain from LGTMing Android PRs.

2016-10-15 23:34 UTC, pingpongboss requested changes
Thank you!

2016-10-15 23:34 UTC, pingpongboss commented on library/src/main/java/com/google/android/material/motion/runtime/Scheduler.java
> +  @Deprecated
Nice, can you also deprecate `Transaction#addPlan`?

2016-10-15 23:34 UTC, pingpongboss commented on library/src/main/java/com/google/android/material/motion/runtime/Scheduler.java
> +    planInfo.plan = plan;
you should set `planInfo.plan = plan.clone()`

2016-10-15 23:34 UTC, pingpongboss commented on library/src/main/java/com/google/android/material/motion/runtime/Scheduler.java
> +   * Adds a plan to this scheduler. Uses {@link PlanInfo} to join the plan and the target together.
I would remove internal details "Uses {@link PlanInfo} to join the plan and the target together" from the public documentation.

2016-10-16 13:37 UTC, seanoshea commented on library/src/main/java/com/google/android/material/motion/runtime/Scheduler.java
> +  @Deprecated
Sure - should be taken care of in https://github.com/material-motion/material-motion-runtime-android/pull/36/commits/37dac4452fdb77b0883108315fa479f94e1a8d37. Haven't deprecated the `addNamedPlan` in the `Transaction` as I think it's probably best to do that in https://github.com/material-motion/material-motion-runtime-android/issues/34?

2016-10-18 00:05 UTC, pingpongboss approved these changes

2016-10-18 00:05 UTC, pingpongboss commented on library/src/main/java/com/google/android/material/motion/runtime/Scheduler.java
> +
remove extra spaces

2016-10-18 00:05 UTC, pingpongboss commented on library/src/main/java/com/google/android/material/motion/runtime/Scheduler.java
> +     */
mis-spacing

2016-10-18 00:55 UTC, jverkoey commented
LGTM.

2016-10-18 01:16 UTC, merged